"""Route table for the textbook web channel.

Handlers still live in ``web_channel.py`` for now. Keeping the URL table here
is the first low-risk step toward splitting the large web backend by domain.
"""


def get_urls():
    return (
        '/', 'RootHandler',
        '/auth/login', 'AuthLoginHandler',
        '/auth/check', 'AuthCheckHandler',
        '/auth/logout', 'AuthLogoutHandler',
        '/message', 'MessageHandler',
        '/upload', 'UploadHandler',
        '/uploads/(.*)', 'UploadsHandler',
        '/api/file', 'FileServeHandler',
        '/poll', 'PollHandler',
        '/stream', 'StreamHandler',
        '/chat', 'ChatHandler',
        '/textbook', 'TextbookPageHandler',
        '/config', 'ConfigHandler',
        '/api/channels', 'ChannelsHandler',
        '/api/weixin/qrlogin', 'WeixinQrHandler',
        '/api/feishu/register', 'FeishuRegisterHandler',
        '/api/tools', 'ToolsHandler',
        '/api/skills', 'SkillsHandler',
        '/api/workspace', 'WorkspaceHandler',
        '/api/memory', 'MemoryHandler',
        '/api/memory/content', 'MemoryContentHandler',
        '/api/memory/query', 'MemoryQueryHandler',
        '/api/knowledge/list', 'KnowledgeListHandler',
        '/api/knowledge/read', 'KnowledgeReadHandler',
        '/api/knowledge/graph', 'KnowledgeGraphHandler',
        '/api/knowledge/upload', 'KnowledgeUploadHandler',
        '/api/knowledge/sources', 'KnowledgeSourcesHandler',
        '/api/knowledge/status', 'KnowledgeStatusHandler',
        '/api/knowledge/link-skill', 'KnowledgeSkillLinkHandler',
        '/api/knowledge/organize', 'KnowledgeOrganizeHandler',
        '/api/knowledge/knowledge-graph', 'KnowledgeKnowledgeGraphHandler',
        '/api/scheduler', 'SchedulerHandler',
        '/api/sessions', 'SessionsHandler',
        '/api/sessions/(.*)/generate_title', 'SessionTitleHandler',
        '/api/sessions/(.*)/clear_context', 'SessionClearContextHandler',
        '/api/sessions/(.*)', 'SessionDetailHandler',
        '/api/history', 'HistoryHandler',
        '/api/logs', 'LogsHandler',
        '/api/version', 'VersionHandler',
        '/api/textbook', 'TextbookHandler',
        '/api/textbook/([^/]+)', 'TextbookDetailHandler',
        '/api/textbook/([^/]+)/outline', 'TextbookOutlineHandler',
        '/api/textbook/([^/]+)/chapters', 'TextbookChaptersHandler',
        '/api/textbook/([^/]+)/chapters/([^/]+)', 'TextbookChapterDetailHandler',
        '/api/textbook/([^/]+)/pipeline', 'TextbookPipelineHandler',
        '/api/textbook/([^/]+)/pipeline/stream', 'TextbookPipelineStreamHandler',
        '/api/textbook/([^/]+)/export', 'TextbookExportHandler',
        '/api/textbook/([^/]+)/outline/versions', 'TextbookOutlineVersionHandler',
        '/api/textbook/([^/]+)/outline/versions/([^/]+)', 'TextbookOutlineVersionDetailHandler',
        '/api/textbook/([^/]+)/outline/versions/([^/]+)/restore', 'TextbookOutlineVersionRestoreHandler',
        '/api/textbook/([^/]+)/review', 'TextbookReviewHandler',
        '/api/textbook/([^/]+)/preferences', 'TextbookPreferencesHandler',
        '/api/textbook/([^/]+)/assets/(.*)', 'TextbookAssetsHandler',
        '/api/sandbox/execute', 'SandboxExecuteHandler',
        '/api/sandbox/charts', 'SandboxChartHandler',
        '/api/chat/save', 'ChatHistorySaveHandler',
        '/api/chat/history/([^/]+)', 'ChatHistoryLoadHandler',
        '/api/chat/sessions', 'ChatSessionsHandler',
        '/api/chat/history/([^/]+)/clear', 'ChatHistoryClearHandler',
        '/api/chat/cancel', 'ChatCancelHandler',
        '/assets/(.*)', 'AssetsHandler',
    )
